config/routes.php
<?php
/**
 * Routes configuration.
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * It's loaded within the context of `Application::routes()` method which
 * receives a `RouteBuilder` instance `$routes` as method argument.
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Routing\Route\DashedRoute;
use Cake\Routing\RouteBuilder;

/*
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 */
/** @var \Cake\Routing\RouteBuilder $routes */
$routes->setRouteClass(DashedRoute::class);

$routes->scope('/', function (RouteBuilder $builder) {
    /*
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, templates/Pages/home.php)...
     */
    $builder->connect('/', ['controller' => 'Websites', 'action' => 'index']);

    $builder->redirect('auth/', ['controller' => 'Auth', 'action' => 'login']);
    /*
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $builder->connect('/pages/*', 'Pages::display');

    /*
     * Connect catchall routes for all controllers.
     *
     * The `fallbacks` method is a shortcut for
     *
     * ```
     * $builder->connect('/:controller', ['action' => 'index']);
     * $builder->connect('/:controller/:action/*', []);
     * ```
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $builder->fallbacks();
});

$routes->prefix('admin', function (RouteBuilder $routes) {
    // Because you are in the admin scope,
    // you do not need to include the /admin prefix
    // or the Admin route element.
    $routes->connect('/', ['prefix'=>false,'controller' => 'Users', 'action' => 'login']);
    $routes->redirect('/users/login', ['prefix'=>false,'controller' => 'Users', 'action' => 'login']);
    $routes->fallbacks(DashedRoute::class);
});

$routes->prefix('student', function (RouteBuilder $routes) {
    // Because you are in the admin scope,
    // you do not need to include the /admin prefix
    // or the Admin route element.
    $routes->connect('/', ['prefix'=>false,'controller' => 'Users', 'action' => 'login']);
    $routes->redirect('/users/login', ['prefix'=>false,'controller' => 'Users', 'action' => 'login']);
    $routes->fallbacks(DashedRoute::class);
});

$routes->prefix('parent', function (RouteBuilder $routes) {
    // Because you are in the admin scope,
    // you do not need to include the /admin prefix
    // or the Admin route element.
    $routes->connect('/', ['prefix'=>false,'controller' => 'Users', 'action' => 'login']);
    $routes->redirect('/users/login', ['prefix'=>false,'controller' => 'Users', 'action' => 'login']);
    $routes->fallbacks(DashedRoute::class);
});

$routes->prefix('teacher', function (RouteBuilder $routes) {
    // Because you are in the admin scope,
    // you do not need to include the /admin prefix
    // or the Admin route element.
    $routes->connect('/', ['prefix'=>false,'controller' => 'Users', 'action' => 'login']);
    $routes->redirect('/users/login', ['prefix'=>false,'controller' => 'Users', 'action' => 'login']);
    $routes->fallbacks(DashedRoute::class);
});

/*
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * $routes->scope('/api', function (RouteBuilder $builder) {
 *     // No $builder->applyMiddleware() here.
 *
 *     // Parse specified extensions from URLs
 *     // $builder->setExtensions(['json', 'xml']);
 *
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Table/ModulesTable.php
<?php
declare(strict_types=1);

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Modules Model
 *
 * @property \App\Model\Table\TeachersTable&\Cake\ORM\Association\BelongsTo $Teachers
 * @property \App\Model\Table\SubjectsTable&\Cake\ORM\Association\BelongsTo $Subjects
 *
 * @method \App\Model\Entity\Module newEmptyEntity()
 * @method \App\Model\Entity\Module newEntity(array $data, array $options = [])
 * @method \App\Model\Entity\Module[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Module get($primaryKey, $options = [])
 * @method \App\Model\Entity\Module findOrCreate($search, ?callable $callback = null, $options = [])
 * @method \App\Model\Entity\Module patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Module[] patchEntities(iterable $entities, array $data, array $options = [])
 * @method \App\Model\Entity\Module|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Module saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Module[]|\Cake\Datasource\ResultSetInterface|false saveMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Module[]|\Cake\Datasource\ResultSetInterface saveManyOrFail(iterable $entities, $options = [])
 * @method \App\Model\Entity\Module[]|\Cake\Datasource\ResultSetInterface|false deleteMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Module[]|\Cake\Datasource\ResultSetInterface deleteManyOrFail(iterable $entities, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class ModulesTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('modules');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Teachers', [
            'foreignKey' => 'teacher_id',
            'joinType' => 'INNER',
        ]);
        $this->belongsTo('Subjects', [
            'foreignKey' => 'subject_id',
            'joinType' => 'INNER',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator): Validator
    {
        $validator
            ->allowEmptyString('id', null, 'create');

        $validator
            ->scalar('title')
            ->maxLength('title', 255)
            ->requirePresence('title', 'create')
            ->notEmptyString('title');

        $validator
            ->scalar('module')
            ->maxLength('module', 255)
            ->allowEmptyString('module');

        $validator
            ->requirePresence('type', 'create')
            ->notEmptyString('type');

        $validator
            ->dateTime('deleted')
            ->allowEmptyDateTime('deleted');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules): RulesChecker
    {
        $rules->add($rules->existsIn(['teacher_id'], 'Teachers'), ['errorField' => 'teacher_id']);
        $rules->add($rules->existsIn(['subject_id'], 'Subjects'), ['errorField' => 'subject_id']);

        return $rules;
    }
}

src/Controller/Admin/StudentsController.php
<?php declare(strict_types=1);

namespace App\Controller\Admin;

use App\Controller\AppController;
use Cake\Event\EventInterface;
use Cake\Filesystem\File;
use Cake\Filesystem\Folder;
use Cake\ORM\TableRegistry;
use Cake\Validation\Validator;

/**
 * Students Controller
 *
 * @method \App\Model\Entity\Student[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class StudentsController extends AppController
{
    protected $Users;
    protected $Teachers;

    public function initialize(): void
    {
        parent::initialize();
        $this->Users = TableRegistry::getTableLocator()->get('Users');
        $this->Teachers = TableRegistry::getTableLocator()->get('Teachers');
    }

    public function beforeFilter(EventInterface $event)
    {
        $this->viewBuilder()->setLayout('admin');
        parent::beforeFilter($event);  // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $students = $this->paginate($this->Students);
        $teachers = $this->Teachers->find('list', [
            'valueField' => function ($query) {
                return strval($query->first_name) . ', ' . strval($query->middle_name) . ', ' . strval($query->last_name);
            },
            'keyField' => function ($query) {
                return $query->id;
            },
        ]);

        $this->set(compact('students', 'teachers'));
    }

    public function getStudents()
    {
        $data = $this->Students->find()->contain(['Teachers']);
        return $this->response
            ->withType('application/json')
            ->withStringBody(json_encode(['data' => $data]));
    }

    public function getStudentsLists()
    {
        $data = $this->Students->find('list',[
            'valueField' => function($query){
                return $query->first_name.' '.$query->middle_name.' '.$query->last_name;
            },
            'keyField' => function($query){
                return $query->id;
            }
        ]);
        return $this->response
            ->withType('application/json')
            ->withStringBody(json_encode($data));
    }

    public function add()
    {
        $user = $this->Users->newEmptyEntity();
        $teachers = $this->Teachers->find('list', [
            'valueField' => function ($query) {
                return strval($query->first_name) . ', ' . strval($query->middle_name) . ', ' . strval($query->last_name);
            },
            'keyField' => function ($query) {
                return $query->id;
            },
        ]);
        if ($this->request->is('post')) {
            $user = $this->Users->patchEntity($user, $this->request->getData());
            // dd($this->request->getData('teacher.first_name'));
            $validator = new Validator();

            $validator
                ->requirePresence('file', 'create')
                ->notEmptyFile('file', ucwords('please upload image!'), false)
                ->add('file', 'file', [
                    'rule' => function ($value) {
                        $extensions = ['image/png', 'image/jpeg', 'image/jpg'];
                        if (!in_array($value->getClientMediaType(), $extensions)) {
                            return ucwords('invalid image format!');
                        }
                        return true;
                    }
                ]);

            // $validator
            //     ->add('teacher', 'custom', [
            //     'rule' => function ($value, $context) {
            //         dd($value['first_name']);
            //         return mb_strlen($value) >= 10;
            //     },
            //     'message' => 'First names need to be at least 10 characters long',
            // ]);

            $validator
                ->requirePresence('confirm_password', 'create')
                ->notEmptyString('confirm_password', ucwords('please confirm your password!'), false)
                ->sameAs('confirm_password', 'password', ucwords('password confirmation not matched!'));

            $errors = $validator->validate($this->request->getData());

            foreach ($errors as $key => $value) {
                $result = ['message' => ucwords(reset($value)), 'result' => ucwords('Error'), 'fields' => $errors];
                return $this->response
                    ->withStatus(422)
                    ->withType('application/json')
                    ->withStringBody(json_encode($result));
            }

            if ($user->hasErrors() == false && strlen($this->request->getData('file')->getClientFileName()) > 0) {
                $file = $this->request->getData('file');

                $filename = uniqid() . $file->getClientFileName();

                $folder = new Folder();

                $path = WWW_ROOT . 'img' . DS . 'user-img';
                if (!$folder->cd($path)) {
                    $folder->create($path);
                }

                $filepath = WWW_ROOT . 'img' . DS . 'user-img' . DS . $filename;

                try {
                    $file->moveTo($filepath);
                    $user->user_image = 'user-img/' . $filename;
                } catch (\Exception $exception) {
                    $user->user_image = 'image not moved';
                }
            }

            $user->is_student = 1;
            $user->token = rand(11111111, 99999999);

            if ($this->Users->save($user)) {
                $result = ['message' => ucwords('The user has been saved.'), 'result' => ucwords('Success')];
                return $this->response
                    ->withStatus(200)
                    ->withType('application/json')
                    ->withStringBody(json_encode($result));
            } else {
                foreach ($user->getErrors() as $key => $value) {
                    $result = ['message' => ucwords(reset($value)), 'result' => ucwords('Error'), 'fields' => $user->getErrors()];
                    return $this->response
                        ->withStatus(422)
                        ->withType('application/json')
                        ->withStringBody(json_encode($result));
                }
            }
        }
        $this->set(compact('user', 'teachers'));
    }

    public function edit($id = null)
    {
        $student = $this->Students->get($id, [
            'contain' => ['Teachers'],
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $student = $this->Students->patchEntity($student, $this->request->getData());
            if ($this->Students->save($student)) {
                $result = ['message' => ucwords('The student has been saved.'), 'result' => ucwords('Success')];
                return $this->response
                    ->withStatus(200)
                    ->withType('application/json')
                    ->withStringBody(json_encode($result));
            } else {
                $result = ['message' => ucwords('The student could not be saved.'), 'result' => ucwords('Error')];
                return $this->response
                    ->withStatus(200)
                    ->withType('application/json')
                    ->withStringBody(json_encode($result));
            }
        }
        return $this->response
            ->withType('application/json')
            ->withStringBody(json_encode($student));
    }

    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $student = $this->Students->get($id);
        if ($this->Students->delete($student)) {
            $result = ['message' => ucwords('The student has been deleted.'), 'result' => ucwords('Success')];
            return $this->response
                ->withStatus(200)
                ->withType('application/json')
                ->withStringBody(json_encode($result));
        } else {
            $result = ['message' => ucwords('The student could not be deleted. Please, try again.'), 'result' => ucwords('Error')];
            return $this->response
                ->withStatus(422)
                ->withType('application/json')
                ->withStringBody(json_encode($result));
        }
    }
}

src/Controller/Student/AudiosController.php
<?php
declare(strict_types=1);

namespace App\Controller\Student;

use App\Controller\AppController;
use Cake\Event\EventInterface;

/**
 * Audios Controller
 *
 * @property \App\Model\Table\AudiosTable $Audios
 * @method \App\Model\Entity\Audio[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class AudiosController extends AppController
{

    public function beforeFilter(EventInterface $event)
    {
        $this->viewBuilder()->setLayout('student');
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function index()
    {
        $audios = $this->Audios->find();
        $this->set(compact('audios'));
    }

}

templates/Student/Modules/index.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Module[]|\Cake\Collection\CollectionInterface $modules
 */
?>
<style>
    li.modules:hover{
        padding: 0.5em 0 !important;
        background-color: #00A5E3;
        transition-delay: 0.1s;
    }
    li.modules:hover i.fa{
        margin-right: 1.5em;
        transition: all 0.5s;
        margin-left: 0.5em;
        transition-delay: 0.1s;
    }
</style>

<?php
    $i = 0;
    $f = 0;
    function generateRandomLightColor() {
        $minBrightness = 150; // Adjust this value to control the minimum brightness

        $red = mt_rand($minBrightness, 255);
        $green = mt_rand($minBrightness, 255);
        $blue = mt_rand($minBrightness, 255);

        $color = sprintf("#%02X%02X%02X", $red, $green, $blue);

        return $color;
    }

function generateRandomSolidColor() {
    $minBrightness = 0; // Adjust this value to control the minimum brightness

    $red = mt_rand($minBrightness, 255);
    $green = mt_rand($minBrightness, 255);
    $blue = mt_rand($minBrightness, 255);

    $color = sprintf("#%02X%02X%02X", $red, $green, $blue);

    return $color;
}
?>
<div class="row h-100" style=" background-image: url(<?=$this->Url->assetUrl('/product-admin/img/new-bg.jpg')?>);background-repeat: no-repeat ;background-size: 100% 100%;object-fit: cover">
    <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 tm-block-col">
        <div class="p-2">
            <ul class="nav nav-tabs tabs" role="tablist">
                <?php foreach ($subjects as $subject):?>
                    <li class="nav-item">
                        <?php
                            $color = generateRandomLightColor();
                        ?>

                        <a class="nav-link <?=($i == 0)? 'active': null;?>" data-toggle="tab" href="#tab-<?=$subject->id?>" style="background-color: <?=($color)?> !important; border-color: <?=($color)?> !important;" role="tab">
                            <?=ucwords($subject->subject)?>
                        </a>
                    </li>
                    <?php $i++;?>
                <?php endforeach;?>
            </ul>
            <div class="tab-content tabs card-block">

                <?php foreach ($subjects as $subject):?>
                    <div class="tab-pane <?=($f == 0)? 'active': null;?>" id="tab-<?=$subject->id?>" role="tabpanel">
                        <div class="col-sm-12 col-md-8 col-lg-8 m-3">
                            <ul style="list-style-type: none !important;;">
                                <?php foreach ($subject->modules as $key => $module):?>
                                    <?php
                                        $color = generateRandomSolidColor();
                                        $filetype = ($module->type)? $module->module: explode('.',$module->module);
                                        $title = ($module->type) ? ucwords('Click to visit link ').($module->module).'.': ucwords('This is ').(strtoupper(@$filetype[1])).' File.';
                                    ?>
                                    <li class="h5 mt-2 modules p-1" style="cursor: pointer;">
                                        <i class="fa fa-chevron-right"></i>
                                        <a href="<?=($module->type)? $module->module: $this->Url->build(['prefix' => 'Student', 'controller' => 'Modules', 'action' => 'download', $module->id]);?>" class="text-dark" title="<?=$title?>">
                                            <?=ucwords($module->title)?>
                                            <?php if(boolval($module->type)):?>
                                                <a style="background: <?=($color)?>; color: #fff; font-size: 0.8em; padding: 0.3em;border-radius: 4em;" href="<?=$this->Url->build(['prefix' => 'Student', 'controller' => 'Modules', 'action' => 'download', $module->id]);?>" target="_blank">Visit Link</a>
                                            <?php else:?>
                                                <?php if(strtolower(@$filetype[1]) == strtolower('pdf')):?>
                                                    <a style="background: <?=($color)?>; color: #fff; font-size: 0.8em; padding: 0.3em;border-radius: 4em;" href="<?=$this->Url->build(['prefix' => 'Student', 'controller' => 'Modules', 'action' => 'download', $module->id]);?>" target="_blank">Download</a>
                                                    <a style="background: <?=($color)?>; color: #fff; font-size: 0.8em; padding: 0.3em;border-radius: 4em;" href="<?=$this->Url->assetUrl('/modules/'.($module->module));?>" target="_blank">Preview</a>
                                                <?php else:?>
                                                    <a style="background: <?=($color)?>; color: #fff; font-size: 0.8em; padding: 0.3em; border-radius: 4em;" href="<?=$this->Url->build(['prefix' => 'Student', 'controller' => 'Modules', 'action' => 'download', $module->id]);?>" target="_blank">Download</a>
                                                <?php endif;?>
                                            <?php endif;?>
                                        </a>
                                    </li>
                                <?php endforeach;?>
                            </ul>
                        </div>
                    </div>
                    <?php $f++;?>
                <?php endforeach;?>

            </div>
        </div>
    </div>
</div>